### ISSUE TITLE
Could you provide paper url and source code of cfl-match?

### ISSUE THREAD

**Issue by jy5275** [shixuansun/SubgraphContainment#1]
Hello~ I'm a undergraduate researching on a topic related to subgraph isomorphism at PKU Data Management Lab (http://mod.icst.pku.edu.cn/english/index.htm). We want to read your excellent work in detail and compare it with some former proposed algorithm. Is it convenient to share the url of your paper titled "_Scaling Up Subgraph Query Processing with Efficient Subgraph Matching_"  and source code of cfl-match (proposed in "_Efficient subgraph matching by postponing cartesian products_") ?  My email is _jyeecs@pku.edu.cn_.

**Comment by shixuansun** [comment]
Thanks for your interest in our paper. The paper URL is [here](https://conferences.computer.org/icde/2019/pdfs/ICDE2019-21DqmQqM7YlfcW2ZceNbB3/6EP5Lb3WfWjkGrW5xHsLtv/12QKuby05pLr0s95TcDzWp.pdf) . We have published the source code of CFQL algorithm in Github. You can download the dataset by following the instruction in the README.md.

For the other algorithms such as CFL, grapes, GGSX, and CT-Index, when we get the source code from their original authors, they only give us the privilege for "private and research usage". So, we cannot share the code with you. We are sorry for that. If you have any further questions, please feel free to contact us.

Thank you.
