### ISSUE TITLE
Request for source code of Light

### ISSUE THREAD

**Issue by sandeep06011991** [shixuansun/SubgraphContainment#2]
Hi I am a PhD student at UMASS, Amherst. 
I have read your paper "Efficient Parallel subgraph enumeration on a single machine" and have enjoyed it immensely. I would like to use your source to compare against my current work on subgraph enumeration. Could you kindly point me towards the source and some build instructions.

**Comment by shixuansun** [comment]
> Hi I am a PhD student at UMASS, Amherst.
> I have read your paper "Efficient Parallel subgraph enumeration on a single machine" and have enjoyed it immensely. I would like to use your source to compare against my current work on subgraph enumeration. Could you kindly point me towards the source and some build instructions.

Hi,
Could you please leave me an email address? I will send the source to you through email.

**Comment by sandeep06011991** [comment]
My email id is 
sandwich06011991@gmail.com 

Or my official email .
spolisetty@cs.umass.edu

**Comment by shixuansun** [comment]
> My email id is
> [sandwich06011991@gmail.com](mailto:sandwich06011991@gmail.com)
> 
> Or my official email .
> [spolisetty@cs.umass.edu](mailto:spolisetty@cs.umass.edu)

Hi, I have sent the source code to your official email. Please check it. If you have any further questions, please feel free to contact us through email.
